server:
    port: 8091

spring:
  datasource:
    username: postgres
    password: commsult
    driverClassName: org.postgresql.Driver
    #the port can be changed later
    url: jdbc:postgresql://localhost:5432/offline-sync
    test-on-borrow: true
    validation-query: SELECT 1
    hikari:
      maxLifeTime: 600000
      minimum-idle: 5
      maximum-pool-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          lob:
            non_contextual_creation: true

  liquibase:
    change-log: "classpath:/liquibase/changelog-master.xml"
    enabled: true